# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 761a6d5b7255d578822861a37aeb3cf50e298230ef9b2d1ce73a03082b74e81c561dc09ab669fdedae302c7796d88f077ff70b8728e93419bc7f550f6192c5be

test:
  secret_key_base: 66f009f58a08fb80274cc686225ec88fa1462cc272e843710fdd28ece515106b4602509a25f53c60c5277d90e2a41fecacd0f00da5e9aef711f91d10ae07d217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
